Repository rancher/eks-operator, pull requests merged in 2024-10, with the labels that each got.

#862 [v1.31] Bump k8s dependencies to support k8s v1.31
  go.mod
  go.sum
Labels: kind/enhancement

#875 [v2.7] Bump Go to 1.20.14
  .trivyignore
  Dockerfile.dapper
  controller/eks-cluster-config-handler.go
Labels: area/go

#877 [v2.7] Bump image version
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  package/Dockerfile
Labels: area/CI, area/release
